project:
  type: website
  output-dir: docs

website:
  title: "Portfólio COPER-MN"

format:
  html:
    title-block-banner: "#003366" # Ativa o banner azul e o deixa da largura da web página
    theme: cosmo
    css: style.css
    toc: true
  

