project:
  type: website
  output-dir: docs

website:
  title: "Portfólio COPER-MN"

format:
  html:
    title-block-banner: "#003366" # Ativa o banner azul
    css: styles.css
    theme: cosmo
    toc: true
    
 